//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLanguage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WM.UI.Mvc.Resources.HomeTexts", typeof(HomeTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almanca.
        /// </summary>
        public static string Almanca {
            get {
                return ResourceManager.GetString("Almanca", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MetaDescription
        /// </summary>
        public static string MetaDescription
        {
            get
            {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string AnaSayfa {
            get {
                return ResourceManager.GetString("AnaSayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancak ihtiyaca göre, çok sayıda nöbet kuralları probleme ilave olmaktadır.
        /// </summary>
        public static string AncakIhtiyacaGore {
            get {
                return ResourceManager.GetString("AncakIhtiyacaGore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni hatırla.
        /// </summary>
        public static string BeniHatırla {
            get {
                return ResourceManager.GetString("BeniHatırla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir başka sorun ise sonradan ortaya çıkan mazeretlerin kurallar ihlal edilmeden göz önünde bulundurulmasıdır.
        /// </summary>
        public static string BirBaskaSorunIseSonradanOrtayaCikanMazeretlerin {
            get {
                return ResourceManager.GetString("BirBaskaSorunIseSonradanOrtayaCikanMazeretlerin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir de olası bir hatada gelecek itirazlar dikkate alındığında &quot;Nöbet Sistemi&quot;nin varlığı önem kazanmaktadır.
        /// </summary>
        public static string BirDeOlasiHatadaGelecekItirazlar {
            get {
                return ResourceManager.GetString("BirDeOlasiHatadaGelecekItirazlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu problemde -en yalın haliyle- hangi periyotta hangi nöbetçilere görev yazılacağına karar verilir.
        /// </summary>
        public static string BuProblemdeEnyalinHaliyle {
            get {
                return ResourceManager.GetString("BuProblemdeEnyalinHaliyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu yönüyle nöbet yazma süreci fazlasıyla zaman, emek ve zihin yorgunluğu oluşturmaktadır.
        /// </summary>
        public static string BuYonuyleNoberYazmaSureci {
            get {
                return ResourceManager.GetString("BuYonuyleNoberYazmaSureci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        public static string Cikis {
            get {
                return ResourceManager.GetString("Cikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylar.
        /// </summary>
        public static string Detaylar {
            get {
                return ResourceManager.GetString("Detaylar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Seçeneği.
        /// </summary>
        public static string DilSecenegi {
            get {
                return ResourceManager.GetString("DilSecenegi", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dil Seçeneği.
        /// </summary>
        public static string DilSecenegiLogo
        {
            get
            {
                return ResourceManager.GetString("DilSecenegiLogo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        public static string Duzenle {
            get {
                return ResourceManager.GetString("Duzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eczacı Odası.
        /// </summary>
        public static string EczaciOdasi {
            get {
                return ResourceManager.GetString("EczaciOdasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eczane.
        /// </summary>
        public static string Eczane {
            get {
                return ResourceManager.GetString("Eczane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eczane Nöbet Sistemi.
        /// </summary>
        public static string EczaneNobetSistemi {
            get {
                return ResourceManager.GetString("EczaneNobetSistemi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elle nöbet yazılırken en çok istenen kurallar bile gözden kaçabilmektedir.
        /// </summary>
        public static string ElleYazilirkenBileEnCokIstenenKuallarGozdenKacabilir {
            get {
                return ResourceManager.GetString("ElleYazilirkenBileEnCokIstenenKuallarGozdenKacabilir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta.
        /// </summary>
        public static string Eposta {
            get {
                return ResourceManager.GetString("Eposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta ya da parola hatalı.
        /// </summary>
        public static string EpostayadaParolaHatali {
            get {
                return ResourceManager.GetString("EpostayadaParolaHatali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel gibi programlar kullanılarak takip edilmeye çalışılan bu listeler, zamanla içinden çıkılmaz bir hale dönüşmektedir.
        /// </summary>
        public static string ExcelGibiProgramlar {
            get {
                return ResourceManager.GetString("ExcelGibiProgramlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faaliyetlerimiz.
        /// </summary>
        public static string Faaliyetlerimiz {
            get {
                return ResourceManager.GetString("Faaliyetlerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string Giris {
            get {
                return ResourceManager.GetString("Giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemşire Nöbet Sistemi.
        /// </summary>
        public static string HemsireNobetSistemi {
            get {
                return ResourceManager.GetString("HemsireNobetSistemi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her nöbet periyodunda gruba yeni katılan ya da gruptan ayrılan nöbetçiler olabilmektedir.
        /// </summary>
        public static string HerNobetPeriyodundaGrubaYeniKatilan {
            get {
                return ResourceManager.GetString("HerNobetPeriyodundaGrubaYeniKatilan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabım.
        /// </summary>
        public static string Hesabim {
            get {
                return ResourceManager.GetString("Hesabim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string Iletisim {
            get {
                return ResourceManager.GetString("Iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce.
        /// </summary>
        public static string Ingilizce {
            get {
                return ResourceManager.GetString("Ingilizce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstatistik.
        /// </summary>
        public static string Istatistik {
            get {
                return ResourceManager.GetString("Istatistik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstatistiklerin keyfini çıkarın.
        /// </summary>
        public static string IstatistiklerinKeyfiniCikarin {
            get {
                return ResourceManager.GetString("IstatistiklerinKeyfiniCikarin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt için iletişime geçin.
        /// </summary>
        public static string KayitIcinIletisimeGecin {
            get {
                return ResourceManager.GetString("KayitIcinIletisimeGecin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Girişi.
        /// </summary>
        public static string KullaniciGirisi {
            get {
                return ResourceManager.GetString("KullaniciGirisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matematik hayatın içinde güzel.
        /// </summary>
        public static string MatematikHayatinIcindeGuzel {
            get {
                return ResourceManager.GetString("MatematikHayatinIcindeGuzel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nöbet Bölgesi.
        /// </summary>
        public static string NobetBolgesi {
            get {
                return ResourceManager.GetString("NobetBolgesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Nöbet&quot; hakkında her şey.
        /// </summary>
        public static string NobetHakkindaHerSey {
            get {
                return ResourceManager.GetString("NobetHakkindaHerSey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nöbetlerin istatistik olarak takip zorunluluğu vardır.
        /// </summary>
        public static string NobetlerinIstatistikOlarakTakipZorunluluguVardır {
            get {
                return ResourceManager.GetString("NobetlerinIstatistikOlarakTakipZorunluluguVardır", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nöbet Sistemi.
        /// </summary>
        public static string NobetSistemi {
            get {
                return ResourceManager.GetString("NobetSistemi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nöbet Sistemi Detaylar.
        /// </summary>
        public static string NobetSistemiDetaylar {
            get {
                return ResourceManager.GetString("NobetSistemiDetaylar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nöbet Yaz.
        /// </summary>
        public static string NobetYaz {
            get {
                return ResourceManager.GetString("NobetYaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nöbet yazmak sanıldığı kadar kolay olmayan ve çok bileşenli bir problemdir.
        /// </summary>
        public static string NobetYazmakSanildigiKadar {
            get {
                return ResourceManager.GetString("NobetYazmakSanildigiKadar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Eczane Ekranı.
        /// </summary>
        public static string OnlineEczaneEkrani {
            get {
                return ResourceManager.GetString("OnlineEczaneEkrani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola.
        /// </summary>
        public static string Parola {
            get {
                return ResourceManager.GetString("Parola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paylaş.
        /// </summary>
        public static string Paylas {
            get {
                return ResourceManager.GetString("Paylas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planlama.
        /// </summary>
        public static string Planlama {
            get {
                return ResourceManager.GetString("Planlama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problemin yapısı gereği binlerce kombinasyon olduğundan                          çözümü elle bulmak bir yana yazılım ile dahi bulmak oldukça zordur.
        /// </summary>
        public static string ProbleminYapisiGeregi {
            get {
                return ResourceManager.GetString("ProbleminYapisiGeregi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referanslarımız.
        /// </summary>
        public static string Referanslarimiz {
            get {
                return ResourceManager.GetString("Referanslarimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saniyeler içinde nöbetleriniz yazılsın.
        /// </summary>
        public static string SaniyelerIcindeNobetlerinizYazilsin {
            get {
                return ResourceManager.GetString("SaniyelerIcindeNobetlerinizYazilsin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siz sadece kurallarınızı belirleyin.
        /// </summary>
        public static string SizSadeceKurallariBelirleyin {
            get {
                return ResourceManager.GetString("SizSadeceKurallariBelirleyin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siz uğraşmayın! Zamanınız size kalsın.
        /// </summary>
        public static string SizUgrasmayinZamaninizSizeKalsin {
            get {
                return ResourceManager.GetString("SizUgrasmayinZamaninizSizeKalsin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Süreç fazlasıyla dinamiktir.
        /// </summary>
        public static string SurecFazlasiylaDinamiktir {
            get {
                return ResourceManager.GetString("SurecFazlasiylaDinamiktir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm cihazlardan ve 7/24 ulaşın.
        /// </summary>
        public static string TumCihazlardan7_24ulasin {
            get {
                return ResourceManager.GetString("TumCihazlardan7/24ulasin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm veriler SSL ile güvende.
        /// </summary>
        public static string TumVerilerSSLileGuvende {
            get {
                return ResourceManager.GetString("TumVerilerSSLileGuvende", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        public static string Turkce {
            get {
                return ResourceManager.GetString("Turkce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ücretsiz demo için bize ulaşın. 
        /// </summary>
        public static string UcretsizDemoIcinBizeUlasin {
            get {
                return ResourceManager.GetString("UcretsizDemoIcinBizeUlasin", resourceCulture);
            }
        }

        /// <summary>
        ///   Hemen başlayalım.
        /// </summary>
        public static string HemenBaslayalim
        {
            get
            {
                return ResourceManager.GetString("HemenBaslayalim", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ürünlerimiz.
        /// </summary>
        public static string Urunlerimiz {
            get {
                return ResourceManager.GetString("Urunlerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama.
        /// </summary>
        public static string Uygulama {
            get {
                return ResourceManager.GetString("Uygulama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazılan Nöbet.
        /// </summary>
        public static string YazilanNobet {
            get {
                return ResourceManager.GetString("YazilanNobet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaman Size Kalsın.
        /// </summary>
        public static string ZamaniSizeKalsin {
            get {
                return ResourceManager.GetString("ZamaniSizeKalsin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Basında Biz.
        /// </summary>
        public static string BasindaBiz
        {
            get
            {
                return ResourceManager.GetString("BasindaBiz", resourceCulture);
            }
        }
    }
}
